#!/usr/bin/env bash
set -Eeuo pipefail

# Generador de contexto — StoHyMoLAP Fase 3.4
# Uso recomendado desde la raíz del repo:
#   bash generar_contexto.sh --with-tests
#
# Objetivo:
#   Empaquetar el estado actual después de Fase 3.3A para continuar en otro chat
#   con Fase 3.4: figuras, tablas finales, auditoría de leakage y redacción publicable.
#
# Este script NO modifica el repo. Solo lee archivos y genera:
#   contextos/stohymolap_contexto_fase3_4_<timestamp>/
#   contextos/stohymolap_contexto_fase3_4_<timestamp>.tar.gz

PROJECT_ROOT="$(pwd)"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
CONTEXT_BASENAME="stohymolap_contexto_fase3_4_${TIMESTAMP}"
CONTEXT_ROOT="contextos/${CONTEXT_BASENAME}"
FILES_ROOT="${CONTEXT_ROOT}/files"
REPORT_MD="${CONTEXT_ROOT}/contexto_stohymolap_fase3_4.md"
PROMPT_MD="${CONTEXT_ROOT}/prompt_siguiente_chat_fase3_4.md"
MANIFEST_TXT="${CONTEXT_ROOT}/manifest.txt"
PKG_FILE="contextos/${CONTEXT_BASENAME}.tar.gz"

WITH_TESTS=0
WITH_FULL_DIFF=0
WITH_OUTPUTS=1
WITH_DATA_HEAD=1
WITH_ENV=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --with-tests)
      WITH_TESTS=1
      ;;
    --with-full-diff)
      WITH_FULL_DIFF=1
      ;;
    --no-outputs)
      WITH_OUTPUTS=0
      ;;
    --no-data-head)
      WITH_DATA_HEAD=0
      ;;
    --no-env)
      WITH_ENV=0
      ;;
    -h|--help)
      cat <<'EOF'
Uso:
  bash generar_contexto.sh [opciones]

Opciones:
  --with-tests      Ejecuta pytest -q y guarda el resultado.
  --with-full-diff  Incluye git diff completo, excluyendo pycache y .pyc.
  --no-outputs      No copia outputs/comparison ni resúmenes por experimento.
  --no-data-head    No incluye cabeceras/muestras de data/*.csv.
  --no-env          No guarda versiones del entorno Python.
EOF
      exit 0
      ;;
    *)
      echo "Opción no reconocida: $1" >&2
      exit 2
      ;;
  esac
  shift
done

mkdir -p "$FILES_ROOT"

run_capture() {
  local outfile="$1"
  shift
  {
    echo "\$ $*"
    echo
    "$@"
  } > "$outfile" 2>&1 || {
    local rc=$?
    echo
    echo "[WARN] comando falló con código ${rc}" >> "$outfile"
    return 0
  }
}

copy_file() {
  local src="$1"
  [[ -f "$src" ]] || return 0
  local dst="${FILES_ROOT}/${src}"
  mkdir -p "$(dirname "$dst")"
  cp -a "$src" "$dst"
}

copy_dir() {
  local src="$1"
  [[ -d "$src" ]] || return 0
  local dst="${FILES_ROOT}/${src}"
  mkdir -p "$(dirname "$dst")"
  cp -a "$src" "$dst"
  find "$dst" -type d -name "__pycache__" -prune -exec rm -rf {} + 2>/dev/null || true
  find "$dst" -type f \( -name "*.pyc" -o -name "*.pyo" -o -name "*.pyd" \) -delete 2>/dev/null || true
  find "$dst" -type d -name ".pytest_cache" -prune -exec rm -rf {} + 2>/dev/null || true
}

append_file_section() {
  local file="$1"
  local title="${2:-$file}"
  {
    echo
    echo "## ${title}"
    echo
    if [[ -f "$file" ]]; then
      echo '```text'
      sed -n '1,220p' "$file"
      local nlines
      nlines="$(wc -l < "$file" | tr -d ' ')"
      if [[ "${nlines}" -gt 220 ]]; then
        echo
        echo "[TRUNCADO: ${nlines} líneas totales; se muestran las primeras 220]"
      fi
      echo '```'
    else
      echo "_No existe: ${file}_"
    fi
  } >> "$REPORT_MD"
}

write_text_file() {
  local dst="$1"
  mkdir -p "$(dirname "$dst")"
  cat > "$dst"
}

# 1) Copia de código/configuración esencial
for f in \
  README.md \
  LICENSE \
  pyproject.toml \
  setup.py \
  setup.cfg \
  requirements.txt \
  requirements-dev.txt \
  environment.yml \
  environment.yaml \
  pytest.ini \
  tox.ini \
  Makefile \
  .gitignore
do
  copy_file "$f"
done

copy_dir "configs"
copy_dir "src/stohymolap"
copy_dir "scripts"
copy_dir "tests"

# Docs: se copian, pero se excluyen caches por copy_dir.
copy_dir "docs"

# 2) Datos: solo cabeceras/muestras para evitar paquetes pesados.
if [[ "$WITH_DATA_HEAD" -eq 1 && -d "data" ]]; then
  mkdir -p "${FILES_ROOT}/data_samples"
  find data -maxdepth 2 -type f \( -name "*.csv" -o -name "*.txt" -o -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) | sort | while read -r f; do
    rel="${f#data/}"
    sample="${FILES_ROOT}/data_samples/${rel}.head.txt"
    mkdir -p "$(dirname "$sample")"
    {
      echo "# Sample of ${f}"
      echo "# Generated by generar_contexto.sh"
      echo
      sed -n '1,80p' "$f"
    } > "$sample" 2>/dev/null || true
  done
fi

# 3) Outputs comparativos y resúmenes por experimento.
if [[ "$WITH_OUTPUTS" -eq 1 ]]; then
  copy_dir "outputs/comparison"

  if [[ -d "outputs/experiments" ]]; then
    mkdir -p "${FILES_ROOT}/outputs/experiments"
    find outputs/experiments -mindepth 1 -maxdepth 1 -type d | sort | while read -r expdir; do
      expname="$(basename "$expdir")"
      dst="${FILES_ROOT}/outputs/experiments/${expname}"
      mkdir -p "$dst"

      for f in \
        config_used.yaml \
        run_metadata.json \
        evaluation_window.json \
        train_metrics.csv \
        validation_metrics.csv \
        validation_metrics_common_intersection.csv \
        regime_metrics_train.csv \
        regime_metrics_validation.csv \
        uncertainty_metrics.csv \
        best_parameters.csv \
        top_k_parameters.csv \
        postprocessing_report.json \
        physical_uncertainty_reference.csv
      do
        [[ -f "${expdir}/${f}" ]] && cp -a "${expdir}/${f}" "${dst}/${f}"
      done

      # Muestras de predicciones, no archivos completos.
      for pred in predictions_train.csv predictions_validation.csv calibration_series.csv validation_series.csv; do
        if [[ -f "${expdir}/${pred}" ]]; then
          {
            echo "# Sample: ${expdir}/${pred}"
            echo "# First 40 lines"
            sed -n '1,40p' "${expdir}/${pred}"
            echo
            echo "# Last 20 lines"
            tail -n 20 "${expdir}/${pred}"
          } > "${dst}/${pred}.sample.txt" 2>/dev/null || true
        fi
      done
    done
  fi
fi

# 4) Diagnóstico Git y entorno.
mkdir -p "${CONTEXT_ROOT}/diagnostics"

run_capture "${CONTEXT_ROOT}/diagnostics/git_status_short.txt" git status --short
run_capture "${CONTEXT_ROOT}/diagnostics/git_log_recent.txt" git log --oneline --decorate -n 20
run_capture "${CONTEXT_ROOT}/diagnostics/git_branch.txt" git branch --show-current
run_capture "${CONTEXT_ROOT}/diagnostics/git_rev_parse_head.txt" git rev-parse HEAD
run_capture "${CONTEXT_ROOT}/diagnostics/git_diff_stat.txt" git diff --stat
run_capture "${CONTEXT_ROOT}/diagnostics/git_staged_diff_stat.txt" git diff --cached --stat
run_capture "${CONTEXT_ROOT}/diagnostics/git_tracked_pycache.txt" bash -lc "git ls-files | grep -E '(__pycache__|\\.py[co]$)' || true"

if [[ "$WITH_FULL_DIFF" -eq 1 ]]; then
  run_capture "${CONTEXT_ROOT}/diagnostics/git_diff_full_no_cache.txt" bash -lc "git diff -- . ':(exclude)*__pycache__*' ':(exclude)*.pyc'"
fi

if [[ "$WITH_ENV" -eq 1 ]]; then
  run_capture "${CONTEXT_ROOT}/diagnostics/python_version.txt" python --version
  run_capture "${CONTEXT_ROOT}/diagnostics/python_key_versions.txt" python - <<'PY'
mods = ["numpy", "pandas", "scipy", "sklearn", "matplotlib", "yaml", "joblib"]
for m in mods:
    try:
        mod = __import__(m)
        print(f"{m}: {getattr(mod, '__version__', 'unknown')}")
    except Exception as exc:
        print(f"{m}: NOT_AVAILABLE ({exc})")
try:
    import torch
    print(f"torch: {torch.__version__}")
except Exception as exc:
    print(f"torch: NOT_AVAILABLE ({exc})")
try:
    import tensorflow as tf
    print(f"tensorflow: {tf.__version__}")
except Exception as exc:
    print(f"tensorflow: NOT_AVAILABLE ({exc})")
try:
    import xgboost
    print(f"xgboost: {xgboost.__version__}")
except Exception as exc:
    print(f"xgboost: NOT_AVAILABLE ({exc})")
PY
fi

run_capture "${CONTEXT_ROOT}/diagnostics/experiment_list.txt" python scripts/run_experiment.py --config configs/experiments.yaml --list

if [[ "$WITH_TESTS" -eq 1 ]]; then
  if command -v pytest >/dev/null 2>&1; then
    run_capture "${CONTEXT_ROOT}/diagnostics/pytest_q.txt" pytest -q
  else
    write_text_file "${CONTEXT_ROOT}/diagnostics/pytest_q.txt" <<'EOF'
pytest no está disponible como comando en este entorno.
Instala pytest o ejecuta con el intérprete correcto.
EOF
  fi
else
  write_text_file "${CONTEXT_ROOT}/diagnostics/pytest_q.txt" <<'EOF'
No se ejecutó pytest. Para incluirlo:
  bash generar_contexto.sh --with-tests
EOF
fi

# 5) Reporte principal.
cat > "$REPORT_MD" <<'EOF'
# Contexto StoHyMoLAP — Fase 3.4

## Estado resumido

Proyecto: StoHyMoLAP  
Fase actual: transición desde Fase 3.3A hacia Fase 3.4.

### Fases cerradas

- Fase 3.0A: saneamiento del paquete, imports y scripts base.
- Fase 3.1: matriz experimental canónica E0–E8.
- Fase 3.2: ventana común de evaluación.
- Fase 3.3A: postproceso auditable Qsim >= 0 para ML/híbridos y leaderboard por intersección común.

### Matriz canónica

- E0_RAMIS_DET_NOBF
- E1_RAMIS_DET_BF
- E2_RAMIS_LEVY_NOBF
- E3_RAMIS_LEVY_BF
- E4_ML_PURE_XGB
- E5_HYB_XGB_MEAN
- E6_HYB_XGB_QUANTILES
- E7_HYB_GRU_MEAN
- E8_HYB_GRU_QUANTILES

### Puntos críticos para revisar en Fase 3.4

1. Auditoría de leakage entre train/validation.
2. Figuras para paper: hidrogramas, FDC, dispersión Qobs-Qsim, residuos por régimen, bandas físicas.
3. Tablas finales: leaderboard común, métricas por régimen, efectos de ablación.
4. Incertidumbre: E2/E3 tienen PICP bajo; no presentar bandas como incertidumbre calibrada sin ajustar.
5. E7/E8 pueden estar usando fallback MLP si no existe TensorFlow/PyTorch. No llamarlos “GRU real” sin confirmar backend.
6. Revisar si el repo aún tiene `__pycache__` o `.pyc` versionados.
7. Evitar incluir `../texto/` u otros directorios externos accidentales.

EOF

append_file_section "${CONTEXT_ROOT}/diagnostics/git_status_short.txt" "Git status corto"
append_file_section "${CONTEXT_ROOT}/diagnostics/git_log_recent.txt" "Commits recientes"
append_file_section "${CONTEXT_ROOT}/diagnostics/git_tracked_pycache.txt" "Archivos cache versionados detectados"
append_file_section "${CONTEXT_ROOT}/diagnostics/experiment_list.txt" "Lista de experimentos"

if [[ -f "outputs/comparison/leaderboard_common_intersection.csv" ]]; then
  append_file_section "outputs/comparison/leaderboard_common_intersection.csv" "Leaderboard común por intersección exacta"
fi
if [[ -f "outputs/comparison/leaderboard.csv" ]]; then
  append_file_section "outputs/comparison/leaderboard.csv" "Leaderboard general"
fi
if [[ -f "outputs/comparison/evaluation_window_comparison.csv" ]]; then
  append_file_section "outputs/comparison/evaluation_window_comparison.csv" "Comparación de ventana de evaluación"
fi
if [[ -f "outputs/comparison/ablation_effects_common_intersection.csv" ]]; then
  append_file_section "outputs/comparison/ablation_effects_common_intersection.csv" "Efectos de ablación en intersección común"
fi
if [[ -f "${CONTEXT_ROOT}/diagnostics/pytest_q.txt" ]]; then
  append_file_section "${CONTEXT_ROOT}/diagnostics/pytest_q.txt" "Resultado de pytest"
fi

cat >> "$REPORT_MD" <<'EOF'

## Archivos incluidos

Ver `manifest.txt`.

## Uso en el siguiente chat

Adjuntar el `.tar.gz` generado y pegar el contenido de `prompt_siguiente_chat_fase3_4.md`.

EOF

# 6) Prompt para el siguiente chat.
cat > "$PROMPT_MD" <<'EOF'
# Prompt para siguiente chat — StoHyMoLAP Fase 3.4

Continuemos con StoHyMoLAP desde Fase 3.4.

## Estado actual

Ya se avanzó la Fase 3 de la matriz experimental de ablaciones:

- Fase 3.0A cerrada: paquete saneado, imports recuperados, scripts base restaurados.
- Fase 3.1 cerrada: matriz canónica E0–E8 definida.
- Fase 3.2 cerrada: ventana común de evaluación implementada.
- Fase 3.3A cerrada funcionalmente: E0–E8 corren y existe leaderboard común por intersección exacta.

Matriz canónica:

1. `E0_RAMIS_DET_NOBF`
2. `E1_RAMIS_DET_BF`
3. `E2_RAMIS_LEVY_NOBF`
4. `E3_RAMIS_LEVY_BF`
5. `E4_ML_PURE_XGB`
6. `E5_HYB_XGB_MEAN`
7. `E6_HYB_XGB_QUANTILES`
8. `E7_HYB_GRU_MEAN`
9. `E8_HYB_GRU_QUANTILES`

## Resultados principales actuales

El leaderboard común por intersección exacta tiene como mejor modelo:

- `E8_HYB_GRU_QUANTILES`: NSE ≈ 0.8491, KGE ≈ 0.8986.
- `E6_HYB_XGB_QUANTILES`: NSE ≈ 0.7399, KGE ≈ 0.8098.
- `E7_HYB_GRU_MEAN`: NSE ≈ 0.6865, KGE ≈ 0.7891.
- `E5_HYB_XGB_MEAN`: NSE ≈ 0.6262, KGE ≈ 0.7146.
- `E4_ML_PURE_XGB`: NSE ≈ 0.5752, KGE ≈ 0.6609.
- Los físicos E0–E3 quedan por debajo en NSE, pero E3 tiene KGE competitivo y conserva valor físico/estocástico.

## Advertencias metodológicas

1. `E7` y `E8` pueden NO ser GRU real si el entorno no tiene TensorFlow/PyTorch. El log indicó fallback MLP sobre secuencias aplanadas. Revisar backend antes de redactar el paper.
2. En Fase 3.3A se implementó postproceso auditable `Qsim = max(Qsim_raw, 0)` solo para ML/híbridos. Revisar `postprocessing_report.json`, especialmente en E8.
3. La incertidumbre física E2/E3 tiene PICP bajo; tratarla como referencia estocástica no calibrada, salvo que se implemente calibración/ensanchar bandas.
4. Revisar si aún hay `__pycache__`/`.pyc` versionados y limpiar Git antes de nuevos commits.
5. No incluir carpetas externas accidentales como `../texto/`.

## Objetivo de Fase 3.4

Preparar la salida publicable:

1. Auditoría de leakage:
   - confirmar que train/validation están separados temporalmente;
   - confirmar que lags/ventanas no usan información futura;
   - confirmar que umbrales de régimen se calculan solo con train;
   - confirmar que la ventana común se aplica consistentemente.
2. Figuras:
   - hidrograma validation para E0/E1/E3/E4/E6/E8;
   - FDC Qobs-Qsim;
   - scatter Qobs-Qsim;
   - residuos por régimen;
   - comparación de componentes Qfast/Qbase/Qtotal;
   - bandas físicas E3/E2 como referencia, con advertencia de subdispersión.
3. Tablas:
   - leaderboard común;
   - métricas por régimen;
   - efectos de ablación;
   - resumen de postproceso ML;
   - estado de backend para E7/E8.
4. README/resultados:
   - actualizar narrativa de Fase 3;
   - distinguir “híbrido secuencial fallback MLP” vs “GRU real”;
   - listar limitaciones.
5. Generar parches por subfase:
   - 3.4A auditoría de leakage y QA;
   - 3.4B figuras;
   - 3.4C tablas paper-ready;
   - 3.4D reporte final.

Primero revisa el contexto adjunto y dime:
- si hay que limpiar Git antes de seguir;
- si E7/E8 deben renombrarse o solo documentar backend;
- qué outputs ya están listos para paper;
- qué parches conviene aplicar en 3.4A.
Después genera el parche 3.4A.
EOF

# 7) Manifest y paquete.
{
  echo "# Manifest — ${CONTEXT_BASENAME}"
  echo "# Generado: $(date -Iseconds)"
  echo
  find "$CONTEXT_ROOT" -type f | sort
} > "$MANIFEST_TXT"

tar -czf "$PKG_FILE" -C "contextos" "$CONTEXT_BASENAME"

echo
echo "Contexto generado:"
echo "  ${REPORT_MD}"
echo
echo "Prompt siguiente chat:"
echo "  ${PROMPT_MD}"
echo
echo "Paquete tar.gz:"
echo "  ${PKG_FILE}"
echo
echo "Adjunta en el siguiente chat el .tar.gz y pega el contenido de:"
echo "  ${PROMPT_MD}"
echo
echo "Sugerencia antes de cambiar de chat:"
echo "  1) Revisa ${CONTEXT_ROOT}/diagnostics/git_tracked_pycache.txt"
echo "  2) Si aparecen .pyc versionados, límpialos antes de seguir."